<?php

define( 'PINTSANDCRAFTS_CORE_VERSION', '1.0.1' );
define( 'PINTSANDCRAFTS_CORE_ABS_PATH', dirname( __FILE__ ) );
define( 'PINTSANDCRAFTS_CORE_REL_PATH', dirname( plugin_basename( __FILE__ ) ) );
define( 'PINTSANDCRAFTS_CORE_URL_PATH', plugin_dir_url( __FILE__ ) );
define( 'PINTSANDCRAFTS_CORE_ASSETS_PATH', PINTSANDCRAFTS_CORE_ABS_PATH . '/assets' );
define( 'PINTSANDCRAFTS_CORE_ASSETS_URL_PATH', PINTSANDCRAFTS_CORE_URL_PATH . 'assets' );
define( 'PINTSANDCRAFTS_CORE_CPT_PATH', PINTSANDCRAFTS_CORE_ABS_PATH . '/post-types' );
define( 'PINTSANDCRAFTS_CORE_CPT_URL_PATH', PINTSANDCRAFTS_CORE_URL_PATH . 'post-types' );
define( 'PINTSANDCRAFTS_CORE_SHORTCODES_PATH', PINTSANDCRAFTS_CORE_ABS_PATH . '/shortcodes' );
define( 'PINTSANDCRAFTS_CORE_SHORTCODES_URL_PATH', PINTSANDCRAFTS_CORE_URL_PATH . 'shortcodes' );